# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=256)),
                ('accountPin', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('safeQuestion', models.CharField(max_length=256)),
                ('safeAnswer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=256)),
                ('money', models.FloatField()),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankId', models.CharField(max_length=256)),
                ('bankName', models.CharField(max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=256)),
                ('date', models.DateTimeField(null=True)),
                ('information', models.CharField(max_length=2048)),
                ('fromAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.Profile'),
        ),
    ]
