# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bankId',
            new_name='bankID',
        ),
    ]
